-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--##################

--## MY PROGRAMS ###

--##################

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use

local alias = {
   terminal = "ghostty",

   fileManager = "dolphin",

   menu = "albert",

   browser = "firefox",

   bar = "waybar"
}

return alias
