-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- #######################################################################################

-- AUTOGENERATED HYPRLAND CONFIG.

-- PLEASE USE THE CONFIG PROVIDED IN THE GIT REPO /examples/hyprland.conf AND EDIT IT,

-- OR EDIT THIS ONE ACCORDING TO THE WIKI INSTRUCTIONS.

-- #######################################################################################

--autogenerated = 1 # remove this line to remove the warning

-- This is an example Hyprland config file.

-- Refer to the wiki for more information.

-- https://wiki.hyprland.org/Configuring/

-- Please note not all available settings / options are set here.

-- For a full list, see the wiki

-- You can split this configuration into multiple files

-- Create your files separately and then link them to this file like this:

-- source = ~/.config/hypr/myColors.conf

--###############

--##  VIDEO   ###

--###############

-- env = AQ_DRM_DEVICES,/dev/dri/card1:/dev/dri/card0

-- source = env.conf -> requires manual conversion
-- local env = require("env")
-- TODO: convert env.conf to .lua and use require()

--###############

--## MONITORS ###

--###############

-- See https://wiki.hyprland.org/Configuring/Monitors/

-- monitor=,preferred,auto,auto

-- monitor=eDP-1,preferred,auto,1.6

-- source = monitors.conf -> requires manual conversion
-- local monitors = require("monitors")
-- TODO: convert monitors.conf to .lua and use require()

--############################

--## ENVIRONMENT VARIABLES ###

--############################

-- See https://wiki.hyprland.org/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", 24)

hl.env("HYPRCURSOR_SIZE", 24)

--####################

--## LOOK AND FEEL ###

--####################

-- Refer to https://wiki.hyprland.org/Configuring/Variables/

-- https://wiki.hyprland.org/Configuring/Variables/#general

hl.config({
   general = {
      gaps_in = 2,
      gaps_out = 2,
      border_size = 2,
      -- https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
      -- Set to true enable resizing windows by clicking and dragging on borders and gaps
      resize_on_border = false,
      -- Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
      allow_tearing = false,
      layout = "dwindle",
      col = {
         active_border = { colors = { "rgba(33ccffee)", "rgba(00ff99ee)" }, angle = 45 },
         inactive_border = "rgba(595959aa)",
      },
   },
})

-- https://wiki.hyprland.org/Configuring/Variables/#decoration

hl.config({
   decoration = {
      rounding = 5,
      rounding_power = 2,
      active_opacity = 1.0,
      inactive_opacity = 0.8,

      shadow = {
         enabled = true,
         range = 4,
         render_power = 3,
         color = "rgba(1a1a1aee)"
      },
      blur = {
         enabled = true,
         size = 3,
         passes = 1,
         vibrancy = 0.1696
      }
   },
   animations = {
      enabled = true
   }
}


)



-- Ref https://wiki.hyprland.org/Configuring/Workspace-Rules/

-- "Smart gaps" / "No gaps when only"

-- uncomment all if you wish to use that.

hl.workspace_rule({
   workspace = "w[tv1]",
   gaps_out = 0,
   gaps_in = 0,
})

hl.workspace_rule({
   workspace = "f[1]",
   gaps_out = 0,
   gaps_in = 0,
})

hl.window_rule({
   name        = "border_size_0",
   match       = {
      workspace = "w[tv1]"
   },
   border_size = 0,
})

hl.window_rule({
   name     = "rounding_0",
   match    = {
      workspace = "w[tv1]"
   },
   rounding = 0,
})

hl.window_rule({
   name        = "border_size_0",
   match       = {
      workspace = "f[1]"
   },
   border_size = 0,
})

hl.window_rule({
   name     = "rounding_0",
   match    = {
      workspace = "f[1]"
   },
   rounding = 0,
})

-- See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more

hl.config({
   dwindle = {
      preserve_split = true,
      -- You probably want this
   },
})

-- See https://wiki.hyprland.org/Configuring/Master-Layout/ for more

hl.config({
   master = {
      new_status = "master",
   },
})

-- https://wiki.hyprland.org/Configuring/Variables/#misc

hl.config({
   misc = {
      force_default_wallpaper = 1,
      -- Set to 0 or 1 to disable the anime mascot wallpapers
      disable_hyprland_logo = true,
      -- If true disables the random hyprland logo / anime girl background. :(
   },
})

--############

--## INPUT ###

--############

-- https://wiki.hyprland.org/Configuring/Variables/#input

hl.config({
   input = {
      follow_mouse = 1,
      sensitivity = 0,
      -- -1.0 - 1.0, 0 means no modification.
      touchpad = {
         natural_scroll = false,
      },
   },
})

-- https://wiki.hyprland.org/Configuring/Variables/#gestures

-- TODO: manual review: gesture = 3, "right", "workspace"

-- Example per-device config

-- See https://wiki.hyprland.org/Configuring/Keywords/#per-device-input-configs for more


-- Custom source files
require("monitors")

require("wallpaper")

require("binds")

require("windowrules")


local alias = require("hyprapps")

hl.on("hyprland.start", function()
   hl.exec_cmd(alias.menu)
   hl.exec_cmd(alias.bar)
end
)
