-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

--###########

-- Monitors #

--###########


function monitor_configure()
   hl.monitor({
      output   = "",
      mode     = "preferred",
      position = "auto",
      scale    = "auto"
   })




   local monitors = hl.get_monitors()
   local monitorCount = #monitors
   hl.notification.create({ text = monitorCount, duration = 10000 })
   local positionText = "0x0"
   if monitorCount == 4 then
      positionText = "4920x0"
   end

   --if monitorCount == 4 then
   hl.workspace_rule({ workspace = "1", monitor = "desc:HP Inc. HP E27 G5 CNC415074V", default = true, persistent = true })
   hl.workspace_rule({ workspace = "2", monitor = "desc:HP Inc. HP E27 G5 CNC4270P2D", default = true, persistent = true })
   hl.workspace_rule({ workspace = "3", monitor = "desc:HP Inc. HP E27 G5 CNC41507D6", default = true, persistent = true })
   hl.workspace_rule({ workspace = "4", monitor = "eDP-1", default = true, persistent = true })
   --end


   hl.monitor({
      output   = "eDP-1",
      mode     = "preferred",
      position = positionText,
      scale    = 1
   })

   hl.monitor({
      output    = "desc:HP Inc. HP E27 G5 CNC415074V",
      mode      = "preferred",
      position  = "0x0",
      scale     = 1,
      transform = 0
   })

   hl.monitor({
      output   = "desc:HP Inc. HP E27 G5 CNC4270P2D",
      mode     = "preferred",
      position = "1920x0",
      scale    = 1
   })

   hl.monitor({
      output    = "desc:HP Inc. HP E27 G5 CNC41507D6",
      mode      = "preferred",
      position  = "3840x0",
      scale     = 1,
      transform = 3
   })


   --if monitorCount == 4 then
   hl.workspace_rule({ workspace = "1", monitor = "desc:HP Inc. HP E27 G5 CNC415074V" })
   hl.workspace_rule({ workspace = "2", monitor = "desc:HP Inc. HP E27 G5 CNC4270P2D" })
   hl.workspace_rule({ workspace = "3", monitor = "desc:HP Inc. HP E27 G5 CNC41507D6" })
   hl.workspace_rule({ workspace = "4", monitor = "eDP-1", default = true })
   --end
end

hl.on("hyprland.start", monitor_configure)
hl.on("config.reloaded", monitor_configure)
