-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Wallpapers control and keybinds


local w1 = "hyprctl hyprpaper wallpaper DP-1,~/wallpaper/tree_blue.png"

local w2 = "hyprctl hyprpaper wallpaper DP-2,~/wallpaper/japanese_bridge.png"

local w3 = "hyprctl hyprpaper wallpaper DP-3,~/wallpaper/house_castle.png"

hl.bind("SUPER" .. " + " .. 1, hl.dsp.exec_cmd("hyprctl hyprpaper wallpaper DP-1,~/wallpaper/tree_blue.png"))

hl.bind("SUPER" .. " + " .. 2, hl.dsp.exec_cmd("hyprctl hyprpaper wallpaper DP-2,~/wallpaper/japanese_bridge.png"))

hl.bind("SUPER" .. " + " .. 3, hl.dsp.exec_cmd("hyprctl hyprpaper wallpaper DP-3,~/wallpaper/house_castle.png"))

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpaper")
end)
