vim.keymap.set("n", "-", "<CMD>Oil --float<CR>", { desc = "Open parent directory" })
vim.keymap.set("n", "gl", function()
	vim.diagnostic.open_float()
end, { desc = "Open VIM diagnostics in Float" })
vim.keymap.set("n", "<leader>cf", function()
	require("conform").format()
end, { desc = "[C]ode [f]ormat the file" })
vim.keymap.set("n", "<leader>le", function()
	vim.diagnostic.open_float(0, { scope = "line" })
end, { desc = "[L]sp show [e]rror" })
